[package]
name = "tekitoi-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = { version = "0.6.0" }
actix-web = { version = "4.0.1" }
anyhow = { version = "1.0" }
clap = { version = "3.0", features = ["derive"] }
config = { version = "0.12", default-features = false, features = ["toml"] }
deadpool-redis = { version = "0.10", features = ["serde"] }
oauth2 = { version = "4.1" }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls"] }
sailfish = { version = "0.4" }
serde = { version = "1" }
serde_qs = { version = "0.9" }
serde_json = { version = "1" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
url = { version = "2.2", default-features = false, features = ["serde"] }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
actix-http = { version = "3.0.0" }
regex = { version = "1" }