base_url = "http://localhost:3000"
log_level = "info"

[database]
type = "sqlite"
url = "sqlite::memory:"

[application.client_name]
client_id = "something"
client_secrets = ["foo", "bar"]
redirect_uri = "http://localhost:8080/api/redirect"

[application.client_name.providers.github]
client_id = "github-client-id"
client_secret = "github-client-secret"

[application.client_name.providers.gitlab]
client_id = "github-client-id"
client_secret = "github-client-secret"
scopes = ["read_user"]

[application.client_name.providers.google]
client_id = "google-client-id"
client_secret = "google-client-secret"
scopes = ["openid", "email", "profile"]
