base_url = "http://localhost:3000"
log_level = "info"

[cache]
url = "redis://localhost"

[clients.client_name]
client_id = "something"
client_secrets = ["foo", "bar"]
redirect_uri = "http://localhost:8080/api/redirect"

[clients.client_name.providers.github]
client_id = "github-client-id"
client_secret = "github-client-secret"

