services:
  demo:
    build: tekitoi-demo
    image: tekitoi-demo
    environment:
      - LOG=debug
      - CLIENT_ID=tekitoi-client-id
      - CLIENT_SECRET=tekitoi-client-secret
      - AUTH_URL=http://localhost:3000/authorize
      - TOKEN_URL=http://localhost:3000/api/access-token
      - BASE_API_URL=http://localhost:3000
      - BASE_URL=http://localhost:8080
    network_mode: host
    # ports:
    #   - 8080:8080

  server:
    build: tekitoi-server
    image: tekitoi-server
    command: --config /config.toml
    environment:
      - BASE_URL=http://localhost:3000
      - LOG_LEVEL=demo
    ports:
      - 3000:3000
    volumes:
      - ./tekitoi-server/config.toml:/config.toml:ro
