name: test demo

on:
  workflow_call:
  pull_request:
    paths:
      - ".github/workflows/demo.yml"
      - "tekitoi-demo/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/demo.yml"
      - "tekitoi-demo/**"

defaults:
  run:
    working-directory: tekitoi-demo

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  linting:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-demo-linting
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt,clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-server-${{ hashFiles('**/Cargo.lock') }}

      - name: run lint
        run: cargo fmt --all --check

      - name: run check
        run: cargo check --all-features --tests

      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests
