name: test server

on:
  workflow_call:
  pull_request:
    paths:
      - ".github/workflows/server.yml"
      - "tekitoi-server/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/server.yml"
      - "tekitoi-server/**"

defaults:
  run:
    working-directory: tekitoi-server

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  testing:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-server-testing
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: install cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: prepare cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-server-${{ hashFiles('**/Cargo.lock') }}

      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: run tests
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info

      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false

  linting:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-server-linting
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt,clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-server-${{ hashFiles('**/Cargo.lock') }}

      - name: run lint
        run: cargo fmt --all --check

      - name: run check
        run: cargo check --all-features --tests

      - name: run clippy
        run: cargo clippy --all-targets --all-features --tests
